--- Logging error ---
Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 48-55: character maps to <undefined>
Call stack:
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\Scripts\pytest.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 76, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\main.py", line 218, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\main.py", line 185, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\main.py", line 225, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\main.py", line 246, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 77, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 92, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 172, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 196, in call_runtest_hook
    treat_keyboard_interrupt_as_exception=item.config.getvalue("usepdb"),
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 212, in __init__
    self.result = func()
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 194, in <lambda>
    lambda: ihook(item=item, **kwds),
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\runner.py", line 122, in pytest_runtest_call
    item.runtest()
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\python.py", line 1425, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\python.py", line 166, in pytest_pyfunc_call
    testfunction(**testargs)
  File "C:\курсова\EasyPayTeamTwo\tests\test_manager\test_task.py", line 24, in test_add_task
    schedule.choose_date_in_modal_add(SCHEDULE_ITEM_DATE)
  File "C:\курсова\EasyPayTeamTwo\src\PageObjects\schedule_page.py", line 38, in choose_date_in_modal_add
    AddScheduleItem.CHOOSE_DATA_EDIT)
  File "C:\курсова\EasyPayTeamTwo\src\PageObjects\page.py", line 70, in send_keys_to_element
    % (data, locator, locator_type))
Message: ' Data \ue003\ue003\ue003\ue003\ue003\ue003\ue003\ue003 successfully send to element with locator: //*[@id="datetimepicker"] and locator type: xpath'
Arguments: ()
